#!/bin/sh -e

if which /usr/bin/openrc-init; then
    ln -sf "openrc-init" "/usr/bin/init"
    echo "	==> Activated OpenRC init."
elif which /usr/bin/runit-init; then
    ln -sf "runit-init" "/usr/bin/init"
    echo "	==> Activated runit init."
fi
